services:
  keycloak:
    image: "quay.io/keycloak/keycloak"
    container_name: "keycloak"
    ports:
      - "8585:8080"
    volumes:
      - keycloak-data:/opt/keycloak
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
    command: ["start-dev"]
volumes:
  keycloak-data:
    driver: local
    driver_opts:
      device: ./keycloak_data/
      o: bind
      type: none
